const mongoose = require('mongoose');
const mongooseSchema = mongoose.Schema;
const OrderMasterSchema = new mongooseSchema({
    order_unique_id : {type: String, required: true, unique: true},
    order_myob_row_id : {type: String, unique: true},
    order_myob_push_status : {type: Boolean, required: true, default: false},
    order_myob_repush_count : {type: Number, default: 0},
    order_myob_pushed_person : {type: mongooseSchema.Types.ObjectId},
    order_myob_repushed_person : {type: mongooseSchema.Types.ObjectId},
    order_myob_session_flag : {type: String, required: true, default: "OFF"},
    order_invoice_id : {type: String},
    order_customer_id : {type: mongooseSchema.Types.ObjectId, required: true},
    order_customer_name : {type: String, required: true },
    order_customer_UID : {type: String, required: true },
    order_customer_contact_name : {type: String, required: true },
    order_customer_contact_phone : {type: String, default: "-"},
    order_customer_contact_email : {type: String, required: true, default: "-" },
    order_delivery_date : {type: Date, required: true },
    order_delivery_date_str : {type: String, required: true },
    order_delivery_time : {type: String, required: true },
    order_delivery_session : {type: String },
    order_GST_EXP_Total : {type: Number, required: true, default: "0" },
    order_Discount_Total : {type: Number, required: true, default: "0" },
    order_GST_Taxable_Total : {type: Number, required: true, default: "0" },
    order_Tax_Total : {type: Number, required: true, default: "0" },
    order_Overall_Price : {type: String, required: true, default: "0" },
    order_status : {type: String, required: true },
    order_delivery_address_mode : {type: String, required: true },
    order_store_delivery_address1 : {type: String, default: "-"},
    order_store_delivery_address2 : {type: String, default: "-"},
    order_store_delivery_city : {type: String, default: "-"},
    order_store_delivery_country : {type: String, default: "AU"},
    order_store_delivery_postalcode : {type: String, default: "-"},
    order_store_delivery_state : {type: String, default: "VIC"},
    order_site_delivery_attention_person : {type: String, default: "-"},
    order_site_delivery_attention_contact : {type: String, default: "-"},
    order_site_delivery_address2 : {type: String, default: "-"},
    order_site_delivery_address1 : {type: String, default: "-"},
    order_site_delivery_address2 : {type: String, default: "-"},
    order_site_delivery_city : {type: String, default: "-"},
    order_site_delivery_details : {type: String, default: "-"},
    order_site_delivery_mud_map : {type: String, default: "-"},
    order_site_delivery_country : {type: String, default: "AU"},
    order_site_delivery_postalcode : {type: String, default: "-"},
    order_site_delivery_state : {type: String, default: "VIC"},
    order_customer_PO_number : {type: String, default: "0"},
    order_flashing_checker : {type: Boolean, default: false},
    order_custom_note : {type: String, default: "-"},
    order_quote_checker_status : {type: Boolean, default: false},
    order_quote_no : {type: mongooseSchema.Types.ObjectId},
    order_quote_id : {type: String,  default: "-"},
    order_quote_price : {type: Number,  default: 0},
    user : {type: mongooseSchema.Types.ObjectId, required: true},
    updated :{type: Date},
    order_images_f: [{ type: String }],
    order_images_fg: [{ type: String }],
    order_images_cl: [{ type: String }],
    order_images_j: [{ type: String }],
    order_images_roof: [{ type: String }],
    order_images_gbi: [{ type: String }],
    order_created_person : {type: mongooseSchema.Types.ObjectId},
    created :{type: Date, default: Date.now},
    order_myob_moved_time_str :{type: String},
    created_str :{type: String},
    order_designed_person : {type: mongooseSchema.Types.ObjectId},
    order_design_assigned_time : {type: Date},
    order_design_completed_time :{type: Date},
    order_qc_status : {type: String, default: "0"},
    order_design_stage : {type: String, default: "0"},
    order_qced_person : {type: mongooseSchema.Types.ObjectId},
    order_qc_assigned_time : {type: Date},
    order_qc_completed_time :{type: Date},
    order_barcode_checker : {type: Boolean, default: false},
    order_barcode_images_f: [{ type: String }],
    order_barcode_images_fg: [{ type: String }],
    order_barcode_images_cl: [{ type: String }],
    order_barcode_images_j: [{ type: String }],
    order_barcode_images_roof: [{ type: String }],
    order_barcode_images_gbi: [{ type: String }],
    order_prod_current_status : {type: String},
    f_order_prod_current_status : {type: String},
    f_order_roll_start_time : {type: Date},
    f_order_roll_end_time : {type: Date},
    f_order_roll_user : {type: mongooseSchema.Types.ObjectId},
    f_order_fold_start_time : {type: Date},
    f_order_fold_end_time : {type: Date},
    f_order_fold_user : {type: mongooseSchema.Types.ObjectId},
    f_order_racking_start_time : {type: Date},
    f_order_racking_end_time : {type: Date},
    f_order_racking_user : {type: mongooseSchema.Types.ObjectId},
    f_order_racking_table : {type: mongooseSchema.Types.ObjectId},
    f_order_racking_dimension1 : {type: String},
    f_order_racking_dimension2 : {type: String},
    cl_order_prod_current_status : {type: String },
    cl_order_fold_start_time : {type: Date},
    cl_order_fold_end_time : {type: Date},
    cl_order_fold_user : {type: mongooseSchema.Types.ObjectId},
    cl_order_racking_start_time : {type: Date},
    cl_order_racking_end_time : {type: Date},
    cl_order_racking_user : {type: mongooseSchema.Types.ObjectId},
    cl_order_racking_table : {type: mongooseSchema.Types.ObjectId},
    cl_order_racking_dimension1 : {type: String},
    cl_order_racking_dimension2 : {type: String},
    j_order_prod_current_status : {type: String},
    j_order_fold_start_time : {type: Date},
    j_order_fold_end_time : {type: Date},
    j_order_fold_user : {type: mongooseSchema.Types.ObjectId},
    j_order_racking_start_time : {type: Date},
    j_order_racking_end_time : {type: Date},
    j_order_racking_user : {type: mongooseSchema.Types.ObjectId},
    j_order_racking_table : {type: mongooseSchema.Types.ObjectId},
    j_order_racking_dimension1 : {type: String},
    j_order_racking_dimension2 : {type: String},
    fg_order_prod_current_status : {type: String},
    fg_order_fold_start_time : {type: Date},
    fg_order_fold_end_time : {type: Date},
    fg_order_fold_user : {type: mongooseSchema.Types.ObjectId},
    fg_order_racking_start_time : {type: Date},
    fg_order_racking_end_time : {type: Date},
    fg_order_racking_user : {type: mongooseSchema.Types.ObjectId},
    fg_order_racking_table : {type: mongooseSchema.Types.ObjectId},
    fg_order_racking_dimension1 : {type: String},
    fg_order_racking_dimension2 : {type: String},
    roof_order_prod_current_status : {type: String},
    roof_order_fold_start_time : {type: Date},
    roof_order_fold_end_time : {type: Date},
    roof_order_fold_user : {type: mongooseSchema.Types.ObjectId},
    roof_order_racking_start_time : {type: Date},
    roof_order_racking_end_time : {type: Date},
    roof_order_racking_user : {type: mongooseSchema.Types.ObjectId},
    roof_order_racking_table : {type: mongooseSchema.Types.ObjectId},
    roof_order_racking_dimension1 : {type: String},
    roof_order_racking_dimension2 : {type: String},
    gbi_order_prod_current_status : {type: String},
    gbi_order_fold_start_time : {type: Date},
    gbi_order_fold_end_time : {type: Date},
    gbi_order_fold_user : {type: mongooseSchema.Types.ObjectId},
    gbi_order_racking_start_time : {type: Date},
    gbi_order_racking_end_time : {type: Date},
    gbi_order_racking_user : {type: mongooseSchema.Types.ObjectId},
    gbi_order_racking_table : {type: mongooseSchema.Types.ObjectId},
    gbi_order_racking_dimension1 : {type: String},
    gbi_order_racking_dimension2 : {type: String},
    order_inter_department_instruction : {type: String},
    f_order_prod_push_status : {type: Number, default: 0},
    fg_order_prod_push_status : {type: Number, default: 0},
    cl_order_prod_push_status : {type: Number, default: 0},
    j_order_prod_push_status : {type: Number, default: 0},
    roof_order_prod_push_status : {type: Number, default: 0},
    gbi_order_prod_push_status : {type: Number, default: 0},
    gbil_order_prod_push_status : {type: Number, default: 0},
    order_master_rack : {type: String},
    f_mail_push_status : {type: Number, default: 0},
    fg_mail_push_status : {type: Number, default: 0},
    j_mail_push_status : {type: Number, default: 0},
    cl_mail_push_status : {type: Number, default: 0},
    roof_mail_push_status : {type: Number, default: 0},
    gbi_mail_push_status : {type: Number, default: 0},
    order_cancelled_user : {type: mongooseSchema.Types.ObjectId},
    order_cancelled_date : {type: Date},
    order_po_checker : {type: Boolean, default: false},
    order_crane_lift_checker : {type: Boolean, default: false},
    order_remake_checker : {type: Boolean, default: false},
    order_loaders_info: {type: String},
    order_doubt_status: {type: String, default: "0"},
    order_supplier_status: {type: String, default: "0"},
    order_far_suburb : {type: Boolean, default: false},
    order_item_qc_status : {type: Number, default: 0},
    order_item_qc_person : {type: mongooseSchema.Types.ObjectId},
    w_order_item_qc_status : {type: Number, default: 0},
    w_order_item_qc_person : {type: mongooseSchema.Types.ObjectId},
    order_priority_status : {type: Number, default: 0},
    order_sales_comment : {type: String},
    order_comment_added_user :  {type: mongooseSchema.Types.ObjectId},
    order_comment_updated_user :  {type: mongooseSchema.Types.ObjectId},
    order_comment_attended_user :  {type: mongooseSchema.Types.ObjectId},
    split: {type: Number, default: 0},
    docket: [{ type: String }],
    order_hold: {type: Boolean, default: false},
    order_hold_person: {type: mongooseSchema.Types.ObjectId},
});
const OrderMaster = mongoose.model('ordermaster', OrderMasterSchema);
module.exports = OrderMaster;