const mongoose = require('mongoose');
const mongooseSchema = mongoose.Schema;
const QuotationMasterSchema = new mongooseSchema({
    quote_unique_id : {type: String, required: true, unique: true},
    quote_myob_row_id : {type: String, unique: true},
    quote_myob_push_status : {type: Boolean, required: true, default: false},
    quote_myob_repush_count : {type: Number, default: 0},
    quote_myob_pushed_person : {type: mongooseSchema.Types.ObjectId},
    quote_myob_repushed_person : {type: mongooseSchema.Types.ObjectId},
    quote_customer_id : {type: mongooseSchema.Types.ObjectId, required: true},
    quote_customer_UID : {type: String, required: true },
    quote_customer_contact_phone : {type: String, default: "-"},
    quote_customer_contact_email : {type: String, required: true, default: "-" },
    quote_customer_PO_number : {type: String, required: true, default: "0" },
    quote_delivery_address_mode : {type: String, required: true },
    quote_delivery_date : {type: Date, required: true },
    quote_delivery_date_str : {type: String, required: true },
    quote_delivery_time : {type: String, required: true },
    quote_delivery_session : {type: String },
    created :{type: Date, default: Date.now},
    created_str :{type: String},
    quote_store_delivery_address1 : {type: String, default: "-"},
    quote_store_delivery_address2 : {type: String, default: "-"},
    quote_store_delivery_city : {type: String, default: "-"},
    quote_store_delivery_country : {type: String, default: "AU"},
    quote_store_delivery_postalcode : {type: String, default: "-"},
    quote_store_delivery_state : {type: String, default: "VIC"},
    quote_site_delivery_attention_person : {type: String, default: "-"},
    quote_site_delivery_attention_contact : {type: String, default: "-"},
    quote_site_delivery_address2 : {type: String, default: "-"},
    quote_site_delivery_address1 : {type: String, default: "-"},
    quote_site_delivery_address2 : {type: String, default: "-"},
    quote_site_delivery_city : {type: String, default: "-"},
    quote_site_delivery_country : {type: String, default: "AU"},
    quote_site_delivery_postalcode : {type: String, default: "-"},
    quote_site_delivery_state : {type: String, default: "VIC"},
    quote_GST_EXP_Total : {type: Number, required: true, default: "0" },
    quote_Discount_Total : {type: Number, required: true, default: "0" },
    quote_GST_Taxable_Total : {type: Number, required: true, default: "0" },
    quote_Tax_Total : {type: Number, required: true, default: "0" },
    quote_Overall_Price : {type: String, required: true, default: "0" },
    quote_custom_note : {type: String},
    quote_inter_department_instruction : {type: String},
    quote_status : {type: String, required: true },
    quote_flashing_checker : {type: Boolean, default: false},
    quote_created_person : {type: mongooseSchema.Types.ObjectId, required: true},
    quote_designed_person : {type: mongooseSchema.Types.ObjectId},
    quote_design_assigned_time : {type: Date},
    quote_design_completed_time :{type: Date},
    quote_qced_person : {type: mongooseSchema.Types.ObjectId},
    quote_qc_assigned_time : {type: Date},
    quote_qc_completed_time :{type: Date},
    quote_qc_status : {type: String, default: "0"},
    quote_design_stage : {type: String, default: "0"},
    quote_customer_name : {type: String, required: true },
    quote_customer_contact_name : {type: String, required: true, default: "-" },
    quote_customer_contact_phone : {type: String, required: true, default: "-" },
    quote_customer_contact_email : {type: String, required: true, default: "-" },
    quote_customer_contact_email : {type: String, required: true, default: "-" },
    quote_Overall_Price : {type: Number, default: 0},
    f_quote_prod_push_status : {type: Number, default: 0},
    fg_quote_prod_push_status : {type: Number, default: 0},
    cl_quote_prod_push_status : {type: Number, default: 0},
    j_quote_prod_push_status : {type: Number, default: 0},
    roof_quote_prod_push_status : {type: Number, default: 0},
    gbi_quote_prod_push_status : {type: Number, default: 0},
    gbil_quote_prod_push_status : {type: Number, default: 0},
    quote_payment_images: [{ type: String }],
    quote_far_suburb : {type: Boolean, default: false},
});
const QuotationMaster = mongoose.model('quotationmaster', QuotationMasterSchema);
module.exports = QuotationMaster;