const checkEnvVariables = (requiredVars) => {
  const missingVars = requiredVars.filter((varName) => !process.env[varName] || process.env[varName].trim() === '');
  if (missingVars.length > 0) {
    throw new Error(`Missing or empty environment variables: ${missingVars.join(', ')}`);
  }
};

const requiredEnvVars = [
  'DB_Username',
  'DB_Password',
  'DB_Cluster',
  'DB_APP_Name',
  'DB_Name',
  'PORT',
  'DEFAULT_PW',
  'ENCRYPTION_KEY',
  'TOKEN_KEY',
  'PW_CH_SEC_Token',
  'From_Email',
  'From_Email_PW',
  'From_Email_CC',
  'Barcode_Email',
  'DesignPDF_Email',
  'FullURL',
  'SQLServerName',
  'SQLPort',
  'SQLUsername',
  'SQLPassword',
  'SQLDataBase',
  'MYOBURL',
  'MasOrdStatus1',
  'MasOrdStatus2',
  'MasOrdStatus3',
  'MasOrdStatus4',
  'MasOrdStatus5',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  '11',
  '12',
  'MYOBURLLogin',
  'MYOBUserName',
  'MYOBPassword',
  'MYOBCompany',
  'MYOBBranch',
  'MYOBPUSHPASSWORD',
  'AWS_REGION',
  'AWS_ACCESS_KEY_ID',
  'AWS_SECRET_ACCESS_KEY',
  'AWS_SES_FROM_EMAIL',
  'TWO_FACTOR_EXPIRE_TIME',
  'To_Daily_Report_Email',
  'Report_Schedule_Hour',
  'Report_Schedule_Min',
  'AWF_CUSTOMER_ID',
  'AWF_ORDER_SERIES',
  'GOOGLE_API_KEY',
  'DAILY_MACHINE_OFFCUTS_REPORT_EMAIL',
  'DAILY_SALES_REPORT_EMAIL',
  'DAILY_EMAIL_REPORT_TIME_H',
  'DAILY_EMAIL_REPORT_TIME_M'
];

module.exports = { checkEnvVariables, requiredEnvVars };